### ISSUE TITLE
Unable to install and use `pandas-profiling`

### ISSUE THREAD

**Issue by kjkoster** [APMonitor/data_science#1]
I am working through the examples and found that installing `pandas-profiling` does not work properly.

When I run `03. Analyze.ipynb`, I am met with the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 profile = ProfileReport(data, explorative=True, minimal=False)

NameError: name 'ProfileReport' is not defined
```

I end up having to manually install and import:

```python
import sys
!{sys.executable} -m pip install pandas pandas-profiling ydata_profiling
!jupyter nbextension enable --py widgetsnbextension

import os
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport

profile = ProfileReport(data, explorative=True, minimal=False)
```

Note how I switch from using `pandas-profiling` to `ydata_profiling`.

See also:
  * https://stackoverflow.com/questions/74996550/pandas-profiling-not-able-to-import-due-to-error-cannot-import-name-dataerror
  * Note how `https://pandas-profiling.ydata.ai/` redirects to `https://ydata-profiling.ydata.ai/`.

It seems that your notebook will need updating to follow breaking changes in `pandas-profiling`.

**Comment by kjkoster** [comment]
Ah, I forgot to mention I am on Python 3.11. That seems significant.

**Comment by APMonitor** [comment]
Thanks for that comment - it looks like pandas-profiling is no longer maintained. I just deleted those sections for now. I may add back in the ydata-profiling at a later time.

**Comment by kjkoster** [comment]
Sweet.

For you to consider: a side effect of that `try`/`except` logic to install modules and restart kernels is that it hides the actual error details. That hinders troubleshooting unforeseen issues like this one.
